#!/usr/bin/env python3
"""Recalibrate Binoculars decision thresholds for a given observer/performer pair.

The threshold shipped in statistical/binoculars/config.py is only valid for
the Falcon-7B / Falcon-7B-Instruct pair it was calibrated on. Any time you
change the model pair (e.g. to a pair that performs better on French text),
you must recalibrate: this script scores a labeled corpus, picks the
threshold that maximizes F1 ("accuracy" mode) and the threshold that hits a
target false-positive rate ("low-fpr" mode), and prints a config.py entry
to paste in.

Usage:
    python scripts/calibrate_binoculars_threshold.py \
        --observer <model> --performer <model> \
        --human-texts-dir <dir of .txt files written by humans> \
        --ai-texts-dir <dir of .txt files generated by an LLM> \
        [--target-fpr 0.0001]

The two text directories should each contain plain .txt files, one document
per file, representative of the language/domain the detector will actually
be run on.
"""

import argparse
from pathlib import Path

import numpy as np
from sklearn.metrics import f1_score

from statistical.binoculars.detector import BinocularsDetector


def _load_texts(directory: Path) -> list[str]:
    return [path.read_text(encoding="utf-8") for path in sorted(directory.glob("*.txt"))]


def _score_all(detector: BinocularsDetector, texts: list[str]) -> list[float]:
    return [detector.compute_score(text) for text in texts]


def _best_f1_threshold(scores: np.ndarray, labels: np.ndarray) -> float:
    """labels: 1 = AI-generated, 0 = human. Binoculars scores are lower for AI text."""
    candidates = np.unique(scores)
    best_threshold, best_f1 = candidates[0], -1.0
    for threshold in candidates:
        predicted_ai = (scores < threshold).astype(int)
        f1 = f1_score(labels, predicted_ai)
        if f1 > best_f1:
            best_f1, best_threshold = f1, threshold
    return float(best_threshold)


def _low_fpr_threshold(human_scores: np.ndarray, target_fpr: float) -> float:
    """Threshold below which at most `target_fpr` fraction of human scores fall."""
    return float(np.percentile(human_scores, target_fpr * 100))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--observer", required=True)
    parser.add_argument("--performer", required=True)
    parser.add_argument("--human-texts-dir", required=True, type=Path)
    parser.add_argument("--ai-texts-dir", required=True, type=Path)
    parser.add_argument("--target-fpr", type=float, default=0.0001)
    args = parser.parse_args()

    human_texts = _load_texts(args.human_texts_dir)
    ai_texts = _load_texts(args.ai_texts_dir)
    if not human_texts or not ai_texts:
        raise ValueError("Both --human-texts-dir and --ai-texts-dir must contain at least one .txt file.")

    # Only compute_score() is used here, so the (not-yet-calibrated) threshold
    # is never touched.
    detector = BinocularsDetector(observer_name_or_path=args.observer, performer_name_or_path=args.performer)

    human_scores = np.array(_score_all(detector, human_texts))
    ai_scores = np.array(_score_all(detector, ai_texts))

    all_scores = np.concatenate([human_scores, ai_scores])
    all_labels = np.concatenate([np.zeros(len(human_scores)), np.ones(len(ai_scores))])

    accuracy_threshold = _best_f1_threshold(all_scores, all_labels)
    low_fpr_threshold = _low_fpr_threshold(human_scores, args.target_fpr)

    print(f"Calibrated on {len(human_texts)} human / {len(ai_texts)} AI texts.")
    print()
    print("Paste into statistical/binoculars/config.py CALIBRATED_THRESHOLDS:")
    print()
    print(f'    ("{args.observer}", "{args.performer}"): CalibratedThresholds(')
    print(f"        accuracy={accuracy_threshold!r},")
    print(f"        low_fpr={low_fpr_threshold!r},  # target FPR={args.target_fpr}")
    print("    ),")


if __name__ == "__main__":
    main()
